apiVersion: apps/v1

kind: Deployment

metadata:
  name: mongo-deployment

  labels:
    app: mongo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo
    # labels can have different key:val, hello:world
    spec:
      containers:
        - name: mongo

          image: mongo:5.0

          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
    # have to match selector label, so it can forward
  ports:
    - protocol: TCP
      port: 8082
      # service port, receive and forward to:27017
      targetPort: 27017
